// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_service_proto protoreflect.FileDescriptor

const file_api_service_proto_rawDesc = "" +
	"\n" +
	"\x11api/service.proto\x12/github.destunna.gogrpccrud.protobuf.api.service\x1a\x0fapi/users.proto2\xf8\x05\n" +
	"\x04User\x12\x95\x01\n" +
	"\n" +
	"CreateUser\x12B.github.destunna.gogrpccrud.protobuf.api.service.CreateUserRequest\x1aC.github.destunna.gogrpccrud.protobuf.api.service.CreateUserResponse\x12\x95\x01\n" +
	"\n" +
	"UpdateUser\x12B.github.destunna.gogrpccrud.protobuf.api.service.UpdateUserRequest\x1aC.github.destunna.gogrpccrud.protobuf.api.service.UpdateUserResponse\x12\x8c\x01\n" +
	"\aGetUser\x12?.github.destunna.gogrpccrud.protobuf.api.service.GetUserRequest\x1a@.github.destunna.gogrpccrud.protobuf.api.service.GetUserResponse\x12\x98\x01\n" +
	"\vGetAllUsers\x12C.github.destunna.gogrpccrud.protobuf.api.service.GetAllUsersRequest\x1aD.github.destunna.gogrpccrud.protobuf.api.service.GetAllUsersResponse\x12\x95\x01\n" +
	"\n" +
	"DeleteUser\x12B.github.destunna.gogrpccrud.protobuf.api.service.DeleteUserRequest\x1aC.github.destunna.gogrpccrud.protobuf.api.service.DeleteUserResponseB\xcf\x02\n" +
	"3com.github.destunna.gogrpccrud.protobuf.api.serviceB\fServiceProtoP\x01Z&github.com/destunna/gogrpccrud/pkg/api\xa2\x02\x06GDGPAS\xaa\x02/Github.Destunna.Gogrpccrud.Protobuf.Api.Service\xca\x02/Github\\Destunna\\Gogrpccrud\\Protobuf\\Api\\Service\xe2\x02;Github\\Destunna\\Gogrpccrud\\Protobuf\\Api\\Service\\GPBMetadata\xea\x024Github::Destunna::Gogrpccrud::Protobuf::Api::Serviceb\x06proto3"

var file_api_service_proto_goTypes = []any{
	(*CreateUserRequest)(nil),   // 0: github.destunna.gogrpccrud.protobuf.api.service.CreateUserRequest
	(*UpdateUserRequest)(nil),   // 1: github.destunna.gogrpccrud.protobuf.api.service.UpdateUserRequest
	(*GetUserRequest)(nil),      // 2: github.destunna.gogrpccrud.protobuf.api.service.GetUserRequest
	(*GetAllUsersRequest)(nil),  // 3: github.destunna.gogrpccrud.protobuf.api.service.GetAllUsersRequest
	(*DeleteUserRequest)(nil),   // 4: github.destunna.gogrpccrud.protobuf.api.service.DeleteUserRequest
	(*CreateUserResponse)(nil),  // 5: github.destunna.gogrpccrud.protobuf.api.service.CreateUserResponse
	(*UpdateUserResponse)(nil),  // 6: github.destunna.gogrpccrud.protobuf.api.service.UpdateUserResponse
	(*GetUserResponse)(nil),     // 7: github.destunna.gogrpccrud.protobuf.api.service.GetUserResponse
	(*GetAllUsersResponse)(nil), // 8: github.destunna.gogrpccrud.protobuf.api.service.GetAllUsersResponse
	(*DeleteUserResponse)(nil),  // 9: github.destunna.gogrpccrud.protobuf.api.service.DeleteUserResponse
}
var file_api_service_proto_depIdxs = []int32{
	0, // 0: github.destunna.gogrpccrud.protobuf.api.service.User.CreateUser:input_type -> github.destunna.gogrpccrud.protobuf.api.service.CreateUserRequest
	1, // 1: github.destunna.gogrpccrud.protobuf.api.service.User.UpdateUser:input_type -> github.destunna.gogrpccrud.protobuf.api.service.UpdateUserRequest
	2, // 2: github.destunna.gogrpccrud.protobuf.api.service.User.GetUser:input_type -> github.destunna.gogrpccrud.protobuf.api.service.GetUserRequest
	3, // 3: github.destunna.gogrpccrud.protobuf.api.service.User.GetAllUsers:input_type -> github.destunna.gogrpccrud.protobuf.api.service.GetAllUsersRequest
	4, // 4: github.destunna.gogrpccrud.protobuf.api.service.User.DeleteUser:input_type -> github.destunna.gogrpccrud.protobuf.api.service.DeleteUserRequest
	5, // 5: github.destunna.gogrpccrud.protobuf.api.service.User.CreateUser:output_type -> github.destunna.gogrpccrud.protobuf.api.service.CreateUserResponse
	6, // 6: github.destunna.gogrpccrud.protobuf.api.service.User.UpdateUser:output_type -> github.destunna.gogrpccrud.protobuf.api.service.UpdateUserResponse
	7, // 7: github.destunna.gogrpccrud.protobuf.api.service.User.GetUser:output_type -> github.destunna.gogrpccrud.protobuf.api.service.GetUserResponse
	8, // 8: github.destunna.gogrpccrud.protobuf.api.service.User.GetAllUsers:output_type -> github.destunna.gogrpccrud.protobuf.api.service.GetAllUsersResponse
	9, // 9: github.destunna.gogrpccrud.protobuf.api.service.User.DeleteUser:output_type -> github.destunna.gogrpccrud.protobuf.api.service.DeleteUserResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_service_proto_init() }
func file_api_service_proto_init() {
	if File_api_service_proto != nil {
		return
	}
	file_api_users_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_service_proto_rawDesc), len(file_api_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_service_proto_goTypes,
		DependencyIndexes: file_api_service_proto_depIdxs,
	}.Build()
	File_api_service_proto = out.File
	file_api_service_proto_goTypes = nil
	file_api_service_proto_depIdxs = nil
}
