// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/users.proto

package api

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Age           string                 `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Habits        string                 `protobuf:"bytes,5,opt,name=habits,proto3" json:"habits,omitempty"`
	Alive         bool                   `protobuf:"varint,6,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_users_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateUserRequest) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *CreateUserRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateUserRequest) GetHabits() string {
	if x != nil {
		return x.Habits
	}
	return ""
}

func (x *CreateUserRequest) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Age           string                 `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Habits        string                 `protobuf:"bytes,5,opt,name=habits,proto3" json:"habits,omitempty"`
	Alive         bool                   `protobuf:"varint,6,opt,name=alive,proto3" json:"alive,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_api_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_api_users_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateUserResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateUserResponse) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *CreateUserResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateUserResponse) GetHabits() string {
	if x != nil {
		return x.Habits
	}
	return ""
}

func (x *CreateUserResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *CreateUserResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Age           string                 `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Habits        string                 `protobuf:"bytes,5,opt,name=habits,proto3" json:"habits,omitempty"`
	Alive         bool                   `protobuf:"varint,6,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_users_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UpdateUserRequest) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *UpdateUserRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UpdateUserRequest) GetHabits() string {
	if x != nil {
		return x.Habits
	}
	return ""
}

func (x *UpdateUserRequest) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Age           string                 `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Habits        string                 `protobuf:"bytes,5,opt,name=habits,proto3" json:"habits,omitempty"`
	Alive         bool                   `protobuf:"varint,6,opt,name=alive,proto3" json:"alive,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_api_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_api_users_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UpdateUserResponse) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *UpdateUserResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UpdateUserResponse) GetHabits() string {
	if x != nil {
		return x.Habits
	}
	return ""
}

func (x *UpdateUserResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *UpdateUserResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_users_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Age           string                 `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Habits        string                 `protobuf:"bytes,5,opt,name=habits,proto3" json:"habits,omitempty"`
	Alive         bool                   `protobuf:"varint,6,opt,name=alive,proto3" json:"alive,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_api_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_api_users_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *GetUserResponse) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *GetUserResponse) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *GetUserResponse) GetHabits() string {
	if x != nil {
		return x.Habits
	}
	return ""
}

func (x *GetUserResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *GetUserResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetAllUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersRequest) Reset() {
	*x = GetAllUsersRequest{}
	mi := &file_api_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersRequest) ProtoMessage() {}

func (x *GetAllUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersRequest.ProtoReflect.Descriptor instead.
func (*GetAllUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_users_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetAllUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*GetUserResponse     `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersResponse) Reset() {
	*x = GetAllUsersResponse{}
	mi := &file_api_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersResponse) ProtoMessage() {}

func (x *GetAllUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersResponse.ProtoReflect.Descriptor instead.
func (*GetAllUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_users_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllUsersResponse) GetUsers() []*GetUserResponse {
	if x != nil {
		return x.Users
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_api_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_api_users_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_api_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_api_users_proto_rawDescGZIP(), []int{9}
}

var File_api_users_proto protoreflect.FileDescriptor

const file_api_users_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/users.proto\x12/github.destunna.gogrpccrud.protobuf.api.service\x1a\x1bbuf/validate/validate.proto\"\xc8\x01\n" +
	"\x11CreateUserRequest\x12&\n" +
	"\tfull_name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18dR\bfullName\x12%\n" +
	"\x03age\x18\x03 \x01(\tB\x13\xbaH\x10r\x0e\x10\x01\x18\x032\b^[0-9]+$R\x03age\x126\n" +
	"\fphone_number\x18\x04 \x01(\tB\x13\xbaH\x10r\x0e\x10\a\x18\x142\b^[0-9]+$R\vphoneNumber\x12\x16\n" +
	"\x06habits\x18\x05 \x01(\tR\x06habits\x12\x14\n" +
	"\x05alive\x18\x06 \x01(\bR\x05alive\"\xc3\x01\n" +
	"\x12CreateUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x10\n" +
	"\x03age\x18\x03 \x01(\tR\x03age\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06habits\x18\x05 \x01(\tR\x06habits\x12\x14\n" +
	"\x05alive\x18\x06 \x01(\bR\x05alive\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"\xee\x01\n" +
	"\x11UpdateUserRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\tB\x14\xbaH\x11\xc8\x01\x01r\f\x10\x012\b^[0-9]+$R\x02id\x12&\n" +
	"\tfull_name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18dR\bfullName\x12%\n" +
	"\x03age\x18\x03 \x01(\tB\x13\xbaH\x10r\x0e\x10\x01\x18\x032\b^[0-9]+$R\x03age\x126\n" +
	"\fphone_number\x18\x04 \x01(\tB\x13\xbaH\x10r\x0e\x10\a\x18\x142\b^[0-9]+$R\vphoneNumber\x12\x16\n" +
	"\x06habits\x18\x05 \x01(\tR\x06habits\x12\x14\n" +
	"\x05alive\x18\x06 \x01(\bR\x05alive\"\xc3\x01\n" +
	"\x12UpdateUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x10\n" +
	"\x03age\x18\x03 \x01(\tR\x03age\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06habits\x18\x05 \x01(\tR\x06habits\x12\x14\n" +
	"\x05alive\x18\x06 \x01(\bR\x05alive\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"6\n" +
	"\x0eGetUserRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\tB\x14\xbaH\x11\xc8\x01\x01r\f\x10\x012\b^[0-9]+$R\x02id\"\xc0\x01\n" +
	"\x0fGetUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x10\n" +
	"\x03age\x18\x03 \x01(\tR\x03age\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06habits\x18\x05 \x01(\tR\x06habits\x12\x14\n" +
	"\x05alive\x18\x06 \x01(\bR\x05alive\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\">\n" +
	"\x12GetAllUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"m\n" +
	"\x13GetAllUsersResponse\x12V\n" +
	"\x05users\x18\x01 \x03(\v2@.github.destunna.gogrpccrud.protobuf.api.service.GetUserResponseR\x05users\"9\n" +
	"\x11DeleteUserRequest\x12$\n" +
	"\x02id\x18\x01 \x01(\tB\x14\xbaH\x11\xc8\x01\x01r\f\x10\x012\b^[0-9]+$R\x02id\"\x14\n" +
	"\x12DeleteUserResponseB\xcd\x02\n" +
	"3com.github.destunna.gogrpccrud.protobuf.api.serviceB\n" +
	"UsersProtoP\x01Z&github.com/destunna/gogrpccrud/pkg/api\xa2\x02\x06GDGPAS\xaa\x02/Github.Destunna.Gogrpccrud.Protobuf.Api.Service\xca\x02/Github\\Destunna\\Gogrpccrud\\Protobuf\\Api\\Service\xe2\x02;Github\\Destunna\\Gogrpccrud\\Protobuf\\Api\\Service\\GPBMetadata\xea\x024Github::Destunna::Gogrpccrud::Protobuf::Api::Serviceb\x06proto3"

var (
	file_api_users_proto_rawDescOnce sync.Once
	file_api_users_proto_rawDescData []byte
)

func file_api_users_proto_rawDescGZIP() []byte {
	file_api_users_proto_rawDescOnce.Do(func() {
		file_api_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_users_proto_rawDesc), len(file_api_users_proto_rawDesc)))
	})
	return file_api_users_proto_rawDescData
}

var file_api_users_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_users_proto_goTypes = []any{
	(*CreateUserRequest)(nil),   // 0: github.destunna.gogrpccrud.protobuf.api.service.CreateUserRequest
	(*CreateUserResponse)(nil),  // 1: github.destunna.gogrpccrud.protobuf.api.service.CreateUserResponse
	(*UpdateUserRequest)(nil),   // 2: github.destunna.gogrpccrud.protobuf.api.service.UpdateUserRequest
	(*UpdateUserResponse)(nil),  // 3: github.destunna.gogrpccrud.protobuf.api.service.UpdateUserResponse
	(*GetUserRequest)(nil),      // 4: github.destunna.gogrpccrud.protobuf.api.service.GetUserRequest
	(*GetUserResponse)(nil),     // 5: github.destunna.gogrpccrud.protobuf.api.service.GetUserResponse
	(*GetAllUsersRequest)(nil),  // 6: github.destunna.gogrpccrud.protobuf.api.service.GetAllUsersRequest
	(*GetAllUsersResponse)(nil), // 7: github.destunna.gogrpccrud.protobuf.api.service.GetAllUsersResponse
	(*DeleteUserRequest)(nil),   // 8: github.destunna.gogrpccrud.protobuf.api.service.DeleteUserRequest
	(*DeleteUserResponse)(nil),  // 9: github.destunna.gogrpccrud.protobuf.api.service.DeleteUserResponse
}
var file_api_users_proto_depIdxs = []int32{
	5, // 0: github.destunna.gogrpccrud.protobuf.api.service.GetAllUsersResponse.users:type_name -> github.destunna.gogrpccrud.protobuf.api.service.GetUserResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_users_proto_init() }
func file_api_users_proto_init() {
	if File_api_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_users_proto_rawDesc), len(file_api_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_users_proto_goTypes,
		DependencyIndexes: file_api_users_proto_depIdxs,
		MessageInfos:      file_api_users_proto_msgTypes,
	}.Build()
	File_api_users_proto = out.File
	file_api_users_proto_goTypes = nil
	file_api_users_proto_depIdxs = nil
}
